### ISSUE TITLE
Support for other areas

### ISSUE THREAD

**Issue by fuzxi** [bepzi/runelite-plugins#1]
Hi, thanks for your work on this plugin. Would you be willing to add support for Inferno and Hallowed Sepulchre? Both of these have varbits to determine when the player is in them, so it shouldn't be much work.
The Inferno varbit is `11878`. It's set to 1 inside the Inferno (and during Tzhaar-Ket-Rak's Jad challenges), and set to 0 everywhere else.
The Hallowed Sepulchre uses the varbit `10392` to store your time remaining on the floor. It's set to 0 outside the Sepulchre, and greater than 0 inside it (even when running out of time, it just stays set to 1 until you leave).

**Comment by bepzi** [comment]
That sounds like a great idea! Might rename the plugin to something like "Automatic Low Detail" if I do that. And thanks for going so far as to fetch the varbits for Inferno and Sepulchre, saves me a bit of time.

If you (or anyone reading this) has any suggestions for areas that could benefit from automatically toggling Low Detail mode, please let me know! Otherwise, my thoughts are:

- Hallowed Sepulchre
- Inferno & Jad Challenges
- DT2 boss arenas (Vardorvis, Leviathan, Sucellus, Whisperer)
- Gauntlet & Corrupted Gauntlet
- Nightmare & Phosani's Nightmare
- Possibly GWD, though that depends -- the instanced versions should be possible at least
- Wilderness boss arenas

**Comment by bepzi** [comment]
Will be closed by https://github.com/runelite/plugin-hub/pull/5010

**Comment by bepzi** [comment]
Version 1.1 merged into the plugin hub, renamed to "Automatic Low Detail" @fuzxi

**Comment by fuzxi** [comment]
Thanks! It works great for Inferno. I'm noticing one issue with Sepulchre, which is that if the plugin is enabled and Sepulchre is unchecked, a "Loading - Please Wait" message pops up every tick along with some lag while inside of the Sepulchre. Probably because that varbit is the timer for Sepulchre and it updates every tick.
