### ISSUE TITLE
cox: Automatic Low Detail breaks layout reloading in Chambers of Xeric

### ISSUE THREAD

**Issue by Jangerberries** [bepzi/runelite-plugins#2]
When the Automatic Low Detail plugin is enabled, reloading the Chambers of Xeric layout using the "Reload" options on the steps inside of the lobby does not update the layout shown by the Chambers of Xeric plugin.

The default Low Detail plugin does not create this behavior.

This is the issue that enables layout reloading when using the "Reload" options on the steps inside of the lobby: https://github.com/runelite/runelite/issues/17241

**Comment by bepzi** [comment]
Thanks for the issue report! I'll look into this.

**Comment by bepzi** [comment]
Interesting, this happens if the Automatic Low Detail plugin is enabled *at all*, not just if the Chambers of Xeric option is turned on.

"Traditional" scouting by leaving the raid still works, but when trying to reload via the stairs the `raids.solver.LayoutSolver` plugin doesn't trigger if the Automatic Low Detail plugin is turned on. Will be interesting to figure out why that is, since Automatic Low Detail *shouldn't* be doing anything to interfere with the raids plugin or the raids state. It only reads the current raids state and manipulates the client's memory mode.

**Comment by hjdarnel** [comment]
hi @bepzi I'm not seeing this as fixed - I just downloaded the plugin from the hub, it seems to make the cox lobby low detail but once I enter the raid it's not anymore

It seems to look "ok" and then reverts to high detail after starting the raid.

**Comment by bepzi** [comment]
> hi @bepzi I'm not seeing this as fixed - I just downloaded the plugin from the hub, it seems to make the cox lobby low detail but once I enter the raid it's not anymore
> 
> It seems to look "ok" and then reverts to high detail after starting the raid.

@hjdarnel That's what I get for being on a break from Chambers :sweat_smile: 

Should have caught this much sooner. Thanks! Opened a new issue here: https://github.com/bepzi/runelite-plugins/issues/4
